// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-VEl9ub4adbHshKYns7msqjAorxxeRrM',
    appId: '1:693912572150:web:329e37b3b14162debe1cd7',
    messagingSenderId: '693912572150',
    projectId: 'boiler-8f150',
    authDomain: 'boiler-8f150.firebaseapp.com',
    storageBucket: 'boiler-8f150.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87l65Jd8FOIkdPwGKz4Coc4Kpozd3Ejs',
    appId: '1:693912572150:android:3dba3625cef436cdbe1cd7',
    messagingSenderId: '693912572150',
    projectId: 'boiler-8f150',
    storageBucket: 'boiler-8f150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHnQk0PeNOadV0ULeIj7CBvWGzfnTJo4',
    appId: '1:693912572150:ios:88f0432545045697be1cd7',
    messagingSenderId: '693912572150',
    projectId: 'boiler-8f150',
    storageBucket: 'boiler-8f150.appspot.com',
    iosClientId: '693912572150-e5rkjje9gaomubcqimhjo2udbhhrgq4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.boiler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHnQk0PeNOadV0ULeIj7CBvWGzfnTJo4',
    appId: '1:693912572150:ios:88f0432545045697be1cd7',
    messagingSenderId: '693912572150',
    projectId: 'boiler-8f150',
    storageBucket: 'boiler-8f150.appspot.com',
    iosClientId: '693912572150-e5rkjje9gaomubcqimhjo2udbhhrgq4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.boiler',
  );
}
